### PR TITLE
Sprint #3052 set pyramid_tm to use explicit transaction manager

### PR DESCRIPTION
**Pull request by chrismorales**
Sets the manager_hook key to pyramid_tm.explicit_manager.

### CODE REVIEW

**Review by mmerickel — COMMENTED** [review]
Does this require any changes to the line numbers in the wiki2 tutorial?

**Comment by stevepiercy** [comment]
There are no line numbering changes in .rst (`:pyobject:` is used in basiclayout.rst and in `definingmodels.rst` there is emphasis for lines 8-9 which is not in the range), but the source files in the `src` directories in each step will need to be updated. I found 7 instances of `settings = config.get_settings()` in files in `docs/tutorials/wiki2/src/*` with filename `__init__.py`.

**Review by stevepiercy — CHANGES_REQUESTED** [review]
Please see my comment for additional files to update in the Pyramid repo.
https://github.com/Pylons/pyramid-cookiecutter-alchemy/pull/10#issuecomment-303250461

**Review by digitalresistor — APPROVED** [review]

**Comment by stevepiercy** [comment]
Merge awaits completion of https://github.com/Pylons/pyramid/pull/3059

**Review by stevepiercy — DISMISSED** [review]
See comment on https://github.com/Pylons/pyramid/pull/3059#pullrequestreview-39888025

**Comment by chrismorales** [comment]
'settings = config.get_settings()'
'settings['tm.manager_hook']` = 'pyramid_tm.explicit_manager'

**Pull request merged**
